### ISSUE TITLE
When making a FromArray deriving shouldn't an enum use fromValue instead of fromName?

### ISSUE THREAD

**Issue by paales** [prolic/fpp#100]
Code generated is:

```
public static function fromArray(array $data): Commission
{
    $condition = \BolCom\RetailerApi\Model\Offer\Condition::fromValue($data['condition']);
}

```

It would make sense in my mind that the value of a payload should use the actual enum value instead of the name of the enum?

**Comment by paales** [comment]
Let me try to explain. In my case I'm not using the types to use it in the prooph event store. I'm getting a payload from an external service (calling something over rest) and want to return a type based on the response:

```php
public function __invoke(GetCommission $getCommission): Commission
{
    $response = $this->client->get("/retailer/commission/{$getCommission->ean()->value()}", [
        'query' => [
            'condition' => $getCommission->condition()->value(),
            'price' => $getCommission->price()->value()
        ],
        'headers' => ['Accept' => 'application/vnd.retailer.v4+json']
    ]);
    return Commission::fromArray($response->getBody()->json());
}
```

I get the actual 'ugly' enum value from the remote system, and want to be able to set the value. Would be nice if I wouldn't have to reformat the response before putting it in a type.

**Comment by paales** [comment]
Oh I see what the system does when there isn't a `while` construct, it just gives all the values an integer number..

**Comment by prolic** [comment]
Sorry what? Which while construct?

I understand that you have a use case where you want fromArray / toArray to use enum values and not enum names. However I am not willing to change this behavior, as I have the other use case more often.

But... There is a solution for both of us:

`Foo deriving (Enum(useValue))`

There is an open ticket to allow to pass options to derivings, but that's not an easy task because it requires to update the parser as well.

I have no time currently to do this, but if you are willing to work on this, let me know.

Still struggling to find out what while construct you are referring to.

**Comment by paales** [comment]
> Sorry what? Which while construct?

I can't type, was a little bit late: I meant the Enum `with(FIELD='bla')` construct.

As for the changes to the parser logic, might be interesting, I'll have to see if I can figure that out.

**Comment by paales** [comment]
Got something working! https://github.com/paales/fpp/pull/2

Will create a PR when i've got the code sniffer thing set up locally.

**Comment by prolic** [comment]
resolved via https://github.com/prolic/fpp/pull/106
